import { useQuery, useQueryClient } from "@tanstack/react-query";
import { MessageSquareText } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/lib/supabase";

type Ticket = { id: string; profile_id: string; subject: string; message: string; status: "aberto" | "em_analise" | "respondido" | "fechado"; admin_note: string | null; created_at: string };
function useTickets() { return useQuery({ queryKey: ["admin-support-tickets"], queryFn: async () => { const { data, error } = await supabase.from("support_tickets").select("id, profile_id, subject, message, status, admin_note, created_at").order("created_at", { ascending: false }).limit(200).returns<Ticket[]>(); if (error) throw error; const ids = [...new Set((data ?? []).map((ticket) => ticket.profile_id))]; const { data: people } = ids.length ? await supabase.from("profiles").select("id, full_name, email").in("id", ids) : { data: [] as { id: string; full_name: string | null; email: string | null }[] }; const names = new Map((people ?? []).map((person) => [person.id, person])); return (data ?? []).map((ticket) => ({ ...ticket, person: names.get(ticket.profile_id) })); }}); }
export function Support() { const { data: tickets = [], isLoading, error } = useTickets(); const queryClient = useQueryClient(); async function update(ticket: Ticket, status: Ticket["status"]) { const note = window.prompt("Resposta ou nota interna (opcional):", ticket.admin_note ?? ""); if (note === null) return; const { error: updateError } = await supabase.from("support_tickets").update({ status, admin_note: note.trim() || null }).eq("id", ticket.id); if (updateError) return toast.error(updateError.message); toast.success("Chamado atualizado."); queryClient.invalidateQueries({ queryKey: ["admin-support-tickets"] }); }
return <div className="p-4 md:p-8 max-w-5xl mx-auto"><h1 className="text-2xl font-extrabold tracking-tight">Suporte</h1><p className="text-sm text-muted-foreground mt-1 mb-6">Chamados enviados pelo app.</p>{isLoading && <p className="text-sm text-muted-foreground">Carregando...</p>}{error && <p className="text-sm text-destructive">Não foi possível carregar. Execute a migration 0043.</p>}{!isLoading && !error && tickets.length === 0 && <div className="rounded-2xl border border-border bg-card p-10 text-center text-muted-foreground"><MessageSquareText className="h-9 w-9 mx-auto mb-3" />Nenhum chamado aberto.</div>}<div className="space-y-3">{tickets.map((ticket) => <article key={ticket.id} className="rounded-2xl border border-border bg-card p-4 md:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{ticket.subject}</p><p className="text-xs text-muted-foreground">{ticket.person?.full_name ?? ticket.person?.email ?? "Usuário"} · {new Date(ticket.created_at).toLocaleString("pt-BR")}</p></div><span className="rounded-full bg-secondary px-2.5 py-1 text-xs font-semibold">{ticket.status.replace("_", " ")}</span></div><p className="mt-3 text-sm whitespace-pre-wrap">{ticket.message}</p>{ticket.admin_note && <p className="mt-3 rounded-xl bg-secondary p-3 text-sm"><b>Nota da equipe:</b> {ticket.admin_note}</p>}<div className="mt-4 flex flex-wrap gap-2"><button onClick={() => update(ticket, "em_analise")} className="h-9 rounded-lg border border-border px-3 text-xs font-semibold">Em análise</button><button onClick={() => update(ticket, "respondido")} className="h-9 rounded-lg bg-primary px-3 text-xs font-semibold text-primary-foreground">Responder</button><button onClick={() => update(ticket, "fechado")} className="h-9 rounded-lg border border-border px-3 text-xs font-semibold">Fechar</button></div></article>)}</div></div>; }
